### ISSUE TITLE
cannot import name 'get_correct_sampler' from 'modules.processing'

### ISSUE THREAD

**Issue by Harvester62** [lilly1987/AI-WEBUI-scripts-Random#2]
After the latest updates to SD Web UI (current installed version is hash [3596af0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3596af07493ab7981ef92074f979eeee8fa624c4)) the "Random grid.py" script doesn't load and returns the following error message in the console:

Error loading script: Random grid.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\scripts\Random grid.py", line 27, in <module>
    from modules.processing import process_images, Processed, get_correct_sampler, StableDiffusionProcessingTxt2Img
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (C:\stable-diffusion-webui\modules\processing.py)

My command line arguments are as follows:
set COMMANDLINE_ARGS=--xformers --opt-split-attention --disable-safe-unpickle --api --deepdanbooru --allow-code --administrator --medvram

My system is Windows 10, 32GB RAM, GTX1070 8GB VRAM, Python 3.10.6, Nvidia Drivers 526.98, CUDA v12.0

Note: the same error happens with the script xyz_plot_grid.py

**Comment by Harvester62** [comment]
Hi, it seems you've fixed the above issue, thank you. A few things I noticed that might need a check:

in the console the following messages are printed that weren't displayed before (a little confusing):

is_img2img : False;
is_img2img : True;

the following warnings are also displayed in the console, twice:

Warning: Bad ui setting value: customscript/Random.py/txt2img/fix width height direction/value: 0; Default value "0" will be used instead.
Warning: Bad ui setting value: customscript/Random.py/img2img/fix width height direction/value: 0; Default value "0" will be used instead.

At line 77 there is a misspelled word, "olny" instead of "only"

In the Web UI, the titles "olny i2i option" and "size" have a large spacing between characters; is it intentional? They look a little strange: "o l n y  i 2 i  o p t i o n" and "s i z e".

Regards.

**Comment by Harvester62** [comment]
I've just noticed that you are no longer maintaining this script, there this bug report is irrelevant and can be closed. Thank you for your attention.

**Comment by holy1017** [comment]
i so sorry

**Comment by Harvester62** [comment]
Don't worry, I do understand that it's better sometimes to focus on a fewer projects. It's fine, really. Thank you.
