### ISSUE TITLE
Random.py - Errors when generating an image

### ISSUE THREAD

**Issue by Harvester62** [lilly1987/AI-WEBUI-scripts-Random#4]
Hi. After clicking on the Generate button, the console displays the following error messages. No images are being generated when this error occurs.

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 980, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 891, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1097, in preprocess
    return self.choices.index(x)

To understand that it was Random.py the source of this error, I had to activate all the scripts one by one, restart Gradio and render an image until the error occurred. I'm telling this because the traceback error doesn't mention any specific script or extension, so I had to find the cause of the problem by trial and error. Thank you for looking into this.

**Comment by lilly1987** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/828438b4a190759807f9054932cae3a8b880ddf1

오늘. 이 버전으로 대응을 한 상태.
업데이트 후.
확인 필요.
Today. Corresponded to this version.
after update.
Need to be confirmed.

**Comment by Harvester62** [comment]
I can confirm the the latest commit on the AUTOMATIC1111 repository is the one you referenced above. Now, the issue and related Traceback error message is different and appears immediately at webui-user.bat startup:

Error loading script: Random.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\scripts\Random.py", line 18, in <module>
    from my import *
ModuleNotFoundError: No module named 'my'

This error prevents the script to be loaded at startup. The module "my" is a test? I've seen it in the root directory of this repository but not being included inside the \scripts folder it is unknown to Python. Just asking for curiosity.

**Comment by holy1017** [comment]
sorry. 
Testing was lacking.  Normal fix based on the latest version.
최신버전 기준. 정상 수정

**Comment by Harvester62** [comment]
I've just tested your script and the error has been fixed, therefore you might wish to close this bug report as resolved. I will have anyway to open a new one, but it's not a severe bug, possibly very easy to fix. Regards.

**Comment by lilly1987** [comment]
ok~
thank you~
